views.py,urls.py,:,The,following,error,is,raised,during,runserver,(,without,basename,kwarg,),:,AssertionError:base_nameargument,not,specified,",",and,could,not,automatically,determine,the,name,from,the,viewset,",",as,it,does,not,have,a.querysetattribute,.,However,",",when,I,add,the,wished,basename,",",the,error,changes,to,:,TypeError,:,as_view(),takes,1,positional,argument,but,2,were,given,I,suspect,that,it,might,be,related,to,combining,a,ViewSet,and,a,ListAPIView,in,one,router,.
