I,am,wondering,why,for,the,code,shown,below,results,in,passing,self,to,function,?,The,call,is,:,Resulting,in,:,TypeError,:,function(),takes,exactly,1,argument,(,2,given,)
