,0
0,I
1,am
2,wondering
3,why
4,for
5,the
6,code
7,shown
8,below
9,results
10,in
11,passing
12,self
13,to
14,function
15,?
16,The
17,call
18,"is:
Resulting in:
TypeError: function()"
19,takes
20,exactly
21,1
22,argument
23,(2
24,given
25,)
