I,am,new,to,both,python,and,django,.,I,am,trying,to,get,python,3.4,and,django,1.6.4,working,within,a,pyvenv-3.4,environment,on,Linux,Mint,Mate,13,.,I,followed,the,procedures,of,Using,a,virtual,environment,with,Python,3.4,for,"""",Building,Python,3.4,from,source,"""",and,"""",Using,pyvenv-3.4,"""",.,Then,following,the,Django,tutorial,at,Writing,your,first,Django,app,",",I,was,able,to,create,"""",mysite,"""",with,startproject,.,But,the,command,"""",python,manage.py,runserver,"""",failed,with,django.core.exceptions,.,ImproperlyConfigured,:,Error,loading,either,pysqlite2,or,sqlite3,modules,(,tried,in,that,order,),:,No,module,named,',_sqlite3,',Sorry,",",I,do,not,recall,why,I,resorted,to,compiling,from,source,",",but,it,may,be,that,I,was,unable,to,find,pyvenv,in,the,standard,Ubuntu,downloads,using,apt-get,.,In,any,case,",",the,Makefile,for,the,source,distribution,does,not,have,an,"""",uninstall,"""",target,",",so,it,seems,I,am,stuck,with,whatever,make,installed,",",and,without,a,plan,for,what,to,do,next,to,actually,get,pyvenv-python-django,working,.,I,am,updating,this,post,by,attaching,the,full,error,:
